version: '3.4'

services:
  backend:
    container_name: backend
    build:
      context: ./project
      dockerfile: Dockerfile
    restart: always
    networks:
      - db
    ports:
      - 7010:8010
    
  frontend:
    container_name: frontend
    build:
      context: ./frontend-parking-management
      dockerfile: Dockerfile
    restart: always
    ports:
      - 10048:5173
    networks:
      - db
    depends_on:
      - backend

networks:
  db:
    driver: bridge
