version: '3.4'

services:
  backend:
    container_name: backend
    build:
      context: ./project
      dockerfile: Dockerfile
    restart: always
    networks:
      - db
    ports:
      - 8010:8010
    expose:
      - 8010
    
  frontend:
    container_name: frontend
    build:
      context: ./frontend-parking-management
      dockerfile: Dockerfile
    restart: always
    ports:
      - 10048:5173
    networks:
      - db
    depends_on:
      - backend

  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount file cấu hình Nginx
  #   ports:
  #     - "8080:80"  # Cổng public (8080) : Cổng trong container (80)
  #   depends_on:
  #     - frontend
  #   networks:
  #   - db

networks:
  db:
    driver: bridge
