version: '3.4'

services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27087:27087"
    networks:
      - db
  data-importer:
    image: mongo
    container_name: data-importer
    volumes:
      - ./data:/data
    command: bash -c "sleep 10 && mongoimport --host mongodb --db paking-management --collection event --file /data/event.json --jsonArray && mongoimport --host mongodb --db paking-management --collection parking --file /data/parking.json --jsonArray && mongoimport --host mongodb --db paking-management --collection parkingTurn --file /data/parkingTurn.json --jsonArray && mongoimport --host mongodb --db paking-management --collection persons --file /data/persons.json --jsonArray && mongoimport --host mongodb --db paking-management --collection vehicles --file /data/vehicles.json --jsonArray"
    depends_on:
      - mongodb
    networks:
      - db
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    networks:
      - db
    ports:
      - 8010:8010
    environment:
      MONGODB_URI: mongodb://mongodb/
    expose:
      - 8010
    depends_on:
      - mongodb
      - data-importer
    
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      VITE_DOMAIN: /api
    ports:
      - 10048:5173
    networks:
      - db
    depends_on:
      - backend

  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount file cấu hình Nginx
  #   ports:
  #     - "8080:80"  # Cổng public (8080) : Cổng trong container (80)
  #   depends_on:
  #     - frontend
  #   networks:
  #   - db

networks:
  db:
    driver: bridge
