version: '3.4'

services:
  backend:
    image: node:18.16.0
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - :8010
    
  frontend:
    image: node:18-alpine
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - :8010


