export const LOCAL_KEY = "EmsLayouts";

const DefaultLayout = {
  DashboardA: {
    xxl: [
      { x: 0, y: 0, w: 6, h: 8 },
      { x: 6, y: 0, w: 5, h: 8 },
      { x: 11, y: 0, w: 5, h: 8 },
      { x: 16, y: 0, w: 5, h: 8 },
      { x: 21, y: 0, w: 5, h: 8 },
      { x: 0, y: 3, w: 13, h: 7 },
      { x: 13, y: 3, w: 13, h: 7 },
      { x: 0, y: 5, w: 13, h: 7 },
      { x: 13, y: 5, w: 13, h: 7 },
    ],
    xl: [
      { x: 0, y: 0, w: 6, h: 8 },
      { x: 6, y: 0, w: 5, h: 8 },
      { x: 11, y: 0, w: 5, h: 8 },
      { x: 16, y: 0, w: 5, h: 8 },
      { x: 21, y: 0, w: 5, h: 8 },
      { x: 0, y: 3, w: 13, h: 7 },
      { x: 13, y: 3, w: 13, h: 7 },
      { x: 0, y: 5, w: 13, h: 7 },
      { x: 13, y: 5, w: 13, h: 7 },
    ],
    lg: [
      { w: 3, h: 8, x: 0, y: 0, i: "card0" },
      { w: 3, h: 8, x: 3, y: 0, i: "card1" },
      { w: 3, h: 8, x: 6, y: 0, i: "card2" },
      { w: 3, h: 8, x: 9, y: 0, i: "card3" },
      { w: 3, h: 8, x: 0, y: 8, i: "card4" },
      { w: 9, h: 8, x: 3, y: 8, i: "card5" },
      { w: 12, h: 7, x: 0, y: 16, i: "card6" },
      { w: 6, h: 7, x: 0, y: 23, i: "card7" },
      { w: 6, h: 7, x: 6, y: 23, i: "card8" },
    ],
    md: [
      { w: 4, h: 8, x: 0, y: 0, i: "card0", moved: false, static: false },
      { w: 4, h: 8, x: 4, y: 0, i: "card1", moved: false, static: false },
      { w: 4, h: 8, x: 8, y: 0, i: "card2", moved: false, static: false },
      { w: 6, h: 8, x: 0, y: 8, i: "card3", moved: false, static: false },
      { w: 6, h: 8, x: 6, y: 8, i: "card4", moved: false, static: false },
      { w: 6, h: 7, x: 6, y: 16, i: "card5", moved: false, static: false },
      { w: 6, h: 7, x: 0, y: 16, i: "card6", moved: false, static: false },
      { w: 6, h: 8, x: 0, y: 23, i: "card7", moved: false, static: false },
      { w: 6, h: 8, x: 6, y: 23, i: "card8", moved: false, static: false },
    ],
    sm: [
      { w: 2, h: 9, x: 0, y: 0, i: "card0", moved: false, static: false },
      { w: 2, h: 9, x: 2, y: 0, i: "card1", moved: false, static: false },
      { w: 2, h: 9, x: 4, y: 0, i: "card2", moved: false, static: false },
      { w: 3, h: 9, x: 0, y: 8, i: "card3", moved: false, static: false },
      { w: 3, h: 9, x: 3, y: 8, i: "card4", moved: false, static: false },
      { w: 6, h: 7, x: 0, y: 16, i: "card5", moved: false, static: false },
      { w: 6, h: 7, x: 0, y: 23, i: "card6", moved: false, static: false },
      { w: 6, h: 7, x: 0, y: 30, i: "card7", moved: false, static: false },
      { w: 6, h: 7, x: 0, y: 37, i: "card8", moved: false, static: false },
    ],
    xs: [
      { w: 4, h: 8, x: 0, y: 0, i: "card0", moved: false, static: false },
      { w: 2, h: 8, x: 2, y: 8, i: "card1", moved: false, static: false },
      { w: 2, h: 8, x: 0, y: 8, i: "card2", moved: false, static: false },
      { w: 2, h: 8, x: 2, y: 16, i: "card3", moved: false, static: false },
      { w: 2, h: 8, x: 0, y: 16, i: "card4", moved: false, static: false },
      { w: 4, h: 7, x: 0, y: 24, i: "card5", moved: false, static: false },
      { w: 4, h: 7, x: 0, y: 31, i: "card6", moved: false, static: false },
      { w: 4, h: 7, x: 0, y: 38, i: "card7", moved: false, static: false },
      { w: 4, h: 7, x: 0, y: 45, i: "card8", moved: false, static: false },
    ],
  },
  DashboardB: {
    xxl: [
      { w: 2, h: 1, x: 0, y: 0, i: "card0" },
      { w: 2, h: 1, x: 0, y: 1, i: "card1" },
      { w: 2, h: 1, x: 0, y: 2, i: "card2" },
      { w: 2, h: 4, x: 0, y: 3, i: "card3" },
      { w: 2, h: 3, x: 0, y: 7, i: "card4" },
      { w: 4, h: 3, x: 2, y: 0, i: "card5" },
      { w: 4, h: 4, x: 2, y: 3, i: "card6" },
      { w: 2, h: 3, x: 2, y: 7, i: "card7" },
      { w: 2, h: 3, x: 4, y: 7, i: "card8" },
    ],
    xl: [
      { w: 2, h: 1, x: 0, y: 0, i: "card0" },
      { w: 2, h: 1, x: 0, y: 1, i: "card1" },
      { w: 2, h: 1, x: 0, y: 2, i: "card2" },
      { w: 2, h: 4, x: 0, y: 3, i: "card3" },
      { w: 2, h: 3, x: 0, y: 7, i: "card4" },
      { w: 4, h: 3, x: 2, y: 0, i: "card5" },
      { w: 4, h: 4, x: 2, y: 3, i: "card6" },
      { w: 2, h: 3, x: 2, y: 7, i: "card7" },
      { w: 2, h: 3, x: 4, y: 7, i: "card8" },
    ],
    lg: [
      { w: 2, h: 1, x: 0, y: 0, i: "card0", moved: false, static: false },
      { w: 2, h: 1, x: 0, y: 1, i: "card1", moved: false, static: false },
      { w: 2, h: 1, x: 0, y: 2, i: "card2", moved: false, static: false },
      { w: 2, h: 4, x: 0, y: 3, i: "card3", moved: false, static: false },
      { w: 2, h: 3, x: 0, y: 7, i: "card4", moved: false, static: false },
      { w: 4, h: 3, x: 2, y: 0, i: "card5", moved: false, static: false },
      { w: 4, h: 4, x: 2, y: 3, i: "card6", moved: false, static: false },
      { w: 2, h: 3, x: 2, y: 7, i: "card7", moved: false, static: false },
      { w: 2, h: 3, x: 4, y: 7, i: "card8", moved: false, static: false },
    ],
    md: [
      { w: 2, h: 1, x: 0, y: 0, i: "card0" },
      { w: 2, h: 1, x: 0, y: 1, i: "card1" },
      { w: 2, h: 1, x: 2, y: 0, i: "card2" },
      { w: 2, h: 4, x: 2, y: 1, i: "card3" },
      { w: 2, h: 3, x: 0, y: 2, i: "card4" },
      { w: 4, h: 3, x: 0, y: 5, i: "card5" },
      { w: 4, h: 3, x: 0, y: 8, i: "card6" },
      { w: 2, h: 3, x: 0, y: 11, i: "card7" },
      { w: 2, h: 3, x: 2, y: 11, i: "card8" },
    ],
    sm: [
      { w: 1, h: 1, x: 0, y: 0, i: "card0" },
      { w: 1, h: 1, x: 1, y: 0, i: "card1" },
      { w: 2, h: 1, x: 0, y: 1, i: "card2" },
      { w: 1, h: 4, x: 1, y: 2, i: "card3" },
      { w: 1, h: 4, x: 0, y: 2, i: "card4" },
      { w: 2, h: 3, x: 0, y: 6, i: "card5" },
      { w: 2, h: 3, x: 0, y: 9, i: "card6" },
      { w: 1, h: 3, x: 0, y: 12, i: "card7" },
      { w: 1, h: 3, x: 1, y: 12, i: "card8" },
    ],
    xs: [
      { w: 1, h: 1, x: 0, y: 0, i: "card0" },
      { w: 1, h: 1, x: 0, y: 1, i: "card1" },
      { w: 1, h: 1, x: 0, y: 2, i: "card2" },
      { w: 1, h: 4, x: 0, y: 3, i: "card3" },
      { w: 1, h: 3, x: 0, y: 7, i: "card4" },
      { w: 1, h: 3, x: 0, y: 10, i: "card5" },
      { w: 1, h: 3, x: 0, y: 13, i: "card6" },
      { w: 1, h: 3, x: 0, y: 16, i: "card7" },
      { w: 1, h: 3, x: 0, y: 19, i: "card8" },
    ],
  },
  DashboardC: {
    xxl: [
      { w: 3, h: 1, x: 0, y: 0, i: "card0" },
      { w: 3, h: 1, x: 3, y: 0, i: "card1" },
      { w: 3, h: 1, x: 6, y: 0, i: "card2" },
      { w: 3, h: 1, x: 9, y: 0, i: "card3" },
      { w: 3, h: 3, x: 0, y: 1, i: "card4" },
      { w: 3, h: 4, x: 0, y: 4, i: "card5" },
      { w: 9, h: 3, x: 3, y: 1, i: "card6" },
      { w: 9, h: 2, x: 3, y: 4, i: "card7" },
      { w: 5, h: 2, x: 3, y: 6, i: "card8" },
      { w: 4, h: 2, x: 8, y: 6, i: "card9" },
    ],
    xl: [
      { w: 3, h: 1, x: 0, y: 0, i: "card0" },
      { w: 3, h: 1, x: 3, y: 0, i: "card1" },
      { w: 3, h: 1, x: 6, y: 0, i: "card2" },
      { w: 3, h: 1, x: 9, y: 0, i: "card3" },
      { w: 3, h: 3, x: 0, y: 1, i: "card4" },
      { w: 3, h: 4, x: 0, y: 4, i: "card5" },
      { w: 9, h: 3, x: 3, y: 1, i: "card6" },
      { w: 9, h: 2, x: 3, y: 4, i: "card7" },
      { w: 5, h: 2, x: 3, y: 6, i: "card8" },
      { w: 4, h: 2, x: 8, y: 6, i: "card9" },
    ],
    lg: [
      { w: 2, h: 1, x: 0, y: 0, i: "card0" },
      { w: 2, h: 1, x: 2, y: 0, i: "card1" },
      { w: 2, h: 1, x: 4, y: 0, i: "card2" },
      { w: 2, h: 1, x: 6, y: 0, i: "card3" },
      { w: 2, h: 3, x: 0, y: 1, i: "card4" },
      { w: 2, h: 4, x: 0, y: 4, i: "card5" },
      { w: 6, h: 3, x: 2, y: 1, i: "card6" },
      { w: 3, h: 4, x: 2, y: 4, i: "card7" },
      { w: 3, h: 2, x: 5, y: 6, i: "card8" },
      { w: 3, h: 2, x: 5, y: 4, i: "card9" },
    ],
    md: [
      { w: 2, h: 1, x: 0, y: 0, i: "card0" },
      { w: 2, h: 1, x: 0, y: 1, i: "card1" },
      { w: 2, h: 1, x: 2, y: 0, i: "card2" },
      { w: 2, h: 1, x: 2, y: 1, i: "card3" },
      { w: 2, h: 3, x: 0, y: 2, i: "card4" },
      { w: 2, h: 5, x: 0, y: 5, i: "card5" },
      { w: 2, h: 2, x: 2, y: 2, i: "card6" },
      { w: 2, h: 2, x: 2, y: 4, i: "card7" },
      { w: 2, h: 2, x: 2, y: 6, i: "card8" },
      { w: 2, h: 2, x: 2, y: 8, i: "card9" },
    ],
    sm: [
      { w: 1, h: 1, x: 0, y: 0, i: "card0" },
      { w: 1, h: 1, x: 1, y: 0, i: "card1" },
      { w: 1, h: 1, x: 0, y: 1, i: "card2" },
      { w: 1, h: 1, x: 1, y: 1, i: "card3" },
      { w: 1, h: 3, x: 0, y: 4, i: "card4" },
      { w: 1, h: 3, x: 0, y: 7, i: "card5" },
      { w: 2, h: 2, x: 0, y: 2, i: "card6" },
      { w: 1, h: 2, x: 1, y: 4, i: "card7" },
      { w: 1, h: 2, x: 1, y: 6, i: "card8" },
      { w: 1, h: 2, x: 1, y: 8, i: "card9" },
    ],
    xs: [
      { w: 1, h: 1, x: 0, y: 0, i: "card0", moved: false, static: false },
      { w: 1, h: 1, x: 0, y: 1, i: "card1", moved: false, static: false },
      { w: 1, h: 1, x: 0, y: 2, i: "card2", moved: false, static: false },
      { w: 1, h: 1, x: 0, y: 3, i: "card3", moved: false, static: false },
      { w: 1, h: 3, x: 0, y: 4, i: "card4", moved: false, static: false },
      { w: 1, h: 4, x: 0, y: 7, i: "card5", moved: false, static: false },
      { w: 1, h: 2, x: 0, y: 11, i: "card6", moved: false, static: false },
      { w: 1, h: 3, x: 0, y: 13, i: "card7", moved: false, static: false },
      { w: 1, h: 2, x: 0, y: 16, i: "card8", moved: false, static: false },
      { w: 1, h: 2, x: 0, y: 18, i: "card9", moved: false, static: false },
    ],
  },
  Report01: {
    xxl: [
      { w: 3, h: 4, x: 0, y: 0, i: "card0" },
      { w: 3, h: 4, x: 3, y: 0, i: "card1" },
      { w: 3, h: 4, x: 6, y: 0, i: "card2" },
      { w: 3, h: 4, x: 9, y: 0, i: "card3" },
      { w: 6, h: 8, x: 0, y: 4, i: "card4" },
      { w: 6, h: 8, x: 6, y: 4, i: "card5" },
      { w: 6, h: 8, x: 0, y: 12, i: "card6" },
      { w: 6, h: 8, x: 6, y: 12, i: "card7" },
    ],
    xl: [
      { w: 3, h: 4, x: 0, y: 0, i: "card0" },
      { w: 3, h: 4, x: 3, y: 0, i: "card1" },
      { w: 3, h: 4, x: 6, y: 0, i: "card2" },
      { w: 3, h: 4, x: 9, y: 0, i: "card3" },
      { w: 6, h: 8, x: 0, y: 4, i: "card4" },
      { w: 6, h: 8, x: 6, y: 4, i: "card5" },
      { w: 6, h: 8, x: 0, y: 12, i: "card6" },
      { w: 6, h: 8, x: 6, y: 12, i: "card7" },
    ],
    lg: [
      { w: 6, h: 4, x: 0, y: 0, i: "card0" },
      { w: 6, h: 4, x: 0, y: 4, i: "card1" },
      { w: 6, h: 4, x: 6, y: 0, i: "card2" },
      { w: 6, h: 4, x: 6, y: 4, i: "card3" },
      { w: 12, h: 8, x: 0, y: 16, i: "card4" },
      { w: 12, h: 8, x: 0, y: 8, i: "card5" },
      { w: 6, h: 8, x: 0, y: 24, i: "card6" },
      { w: 6, h: 8, x: 6, y: 24, i: "card7" },
    ],
    md: [
      { w: 6, h: 4, x: 0, y: 0, i: "card0" },
      { w: 6, h: 4, x: 0, y: 4, i: "card1" },
      { w: 6, h: 4, x: 6, y: 0, i: "card2" },
      { w: 6, h: 4, x: 6, y: 4, i: "card3" },
      { w: 12, h: 8, x: 0, y: 16, i: "card4" },
      { w: 12, h: 8, x: 0, y: 8, i: "card5" },
      { w: 6, h: 8, x: 0, y: 24, i: "card6" },
      { w: 6, h: 8, x: 6, y: 24, i: "card7" },
    ],
    sm: [
      { w: 6, h: 4, x: 0, y: 0, i: "card0" },
      { w: 6, h: 4, x: 0, y: 4, i: "card1" },
      { w: 6, h: 4, x: 6, y: 0, i: "card2" },
      { w: 6, h: 4, x: 6, y: 4, i: "card3" },
      { w: 12, h: 8, x: 0, y: 16, i: "card4" },
      { w: 12, h: 8, x: 0, y: 8, i: "card5" },
      { w: 6, h: 8, x: 0, y: 24, i: "card6" },
      { w: 6, h: 8, x: 6, y: 24, i: "card7" },
    ],
    xs: [
      { w: 6, h: 4, x: 0, y: 0, i: "card0" },
      { w: 6, h: 4, x: 0, y: 4, i: "card1" },
      { w: 6, h: 4, x: 6, y: 0, i: "card2" },
      { w: 6, h: 4, x: 6, y: 4, i: "card3" },
      { w: 12, h: 8, x: 0, y: 16, i: "card4" },
      { w: 12, h: 8, x: 0, y: 8, i: "card5" },
      { w: 6, h: 8, x: 0, y: 24, i: "card6" },
      { w: 6, h: 8, x: 6, y: 24, i: "card7" },
    ],
  },
};

const Layouts = (
  Dl = {},
  breakpoints = { xxl: 1600, xl: 1200, lg: 992, md: 768, sm: 576, xs: 0 }
) => {
  const rs = Object.keys(breakpoints).reduce((acc, curr) => {
    return {
      ...acc,
      [curr]: Dl[curr] || [],
    };
  }, {});
  return rs;
};

export const GetDefaultLayouts = (layoutKey) => {
  return Layouts(DefaultLayout[layoutKey]);
};

export const GetLayouts = (layoutKey) => {
  // Get from localStorage
  const localLayouts = JSON.parse(localStorage.getItem(LOCAL_KEY)) || {};
  const defaultByKey = DefaultLayout[layoutKey];
  const layoutByKey = localLayouts[layoutKey];
  const rs = {
    ...defaultByKey,
    ...layoutByKey,
  };
  if (layoutByKey && typeof layoutByKey === "object") return Layouts(rs);

  console.log('default');

  return GetDefaultLayouts(layoutKey);
};
