name: Deploy

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Install SSH key
    #   uses: webfactory/ssh-agent@v0.5.3
    #   with:
    #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy over SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USERNAME }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        script: |
          echo "Listing files and folders in /path/to/your/remote/project"
          for item in ./*; do
            echo "$(basename "$item")"
          done
          # if [ -d "/project/20110677_20110642/parking-management" ]; then
          #   echo "Path exists. Pulling latest code and deploying..."
          #   cd /project/20110677_20110642/parking-management
          #   git pull origin main
          #   docker-compose down
          #   docker-compose up -d
          # else
          #   echo "Path does not exist."
          #   exit 1
          # fi



   
